"""lark_alert Python 示例。

运行前先执行 `uv run maturin develop` 安装扩展模块，并设置：

- LARK_WEBHOOK_URL：飞书自定义机器人 Webhook 地址
- LARK_SECRET：可选，机器人开启签名校验时填写
"""

import os

from lark_alert import Card, LarkAlert, PostMessage, Severity


def main() -> None:
    webhook_url = os.getenv("LARK_WEBHOOK_URL", "").strip()
    if not webhook_url:
        raise SystemExit("请设置 LARK_WEBHOOK_URL 环境变量")

    secret = os.getenv("LARK_SECRET") or None
    alert = LarkAlert(webhook_url, secret=secret, timeout_secs=10, max_retries=2)

    # 1. 普通文本
    alert.send_text("lark_alert Python 示例：普通文本")

    # 2. 富文本 post
    post = PostMessage("lark_alert 示例").text_line("第一行").text_line("第二行")
    alert.send_post(post)

    # 3. 统一样式卡片
    card = (
        Card()
        .severity(Severity.Warning)
        .title("磁盘使用率过高")
        .summary("disk / 使用率 92%")
        .service("prometheus")
        .environment("prod")
        .timestamp("2026-01-01T00:00:00Z")
        .field("host", "10.0.0.1")
        .wide_field("mount", "/")
        .details("持续 10 分钟超过 90% 阈值")
        .note("auto-generated by lark_alert")
    )
    alert.send_card(card)


if __name__ == "__main__":
    main()
