"""lark_alert Python 示例。

本示例使用你提供的测试 Webhook；如需生产使用请替换为自己的 Webhook 地址。
运行前先执行 `uv run maturin develop` 安装扩展模块。
"""

from lark_alert import Card, LarkAlert, PostMessage, Severity, TextMessage

# 测试用 Webhook（用户提供）
WEBHOOK_URL = ""


def main() -> None:
    alert = LarkAlert(WEBHOOK_URL, timeout_secs=10, max_retries=2)

    # 1. 普通文本
    alert.send_text("lark_alert Python 示例：普通文本")

    # 2. 富文本 post
    post = PostMessage("lark_alert 示例").text_line("第一行").text_line("第二行")
    alert.send_post(post)

    # 3. 统一样式卡片
    card = (
        Card()
        .severity(Severity.Warning)
        .title("磁盘使用率过高")
        .summary("disk / 使用率 92%")
        .service("prometheus")
        .environment("prod")
        .timestamp("2026-01-01T00:00:00Z")
        .field("host", "10.0.0.1")
        .field("mount", "/")
        .details("持续 10 分钟超过 90% 阈值")
        .note("auto-generated by lark_alert")
    )
    alert.send_card(card)

    # 4. 签名机器人（如果开启签名，请设置 secret）
    # signed = LarkAlert(WEBHOOK_URL, secret="your-secret")
    # signed.send_text("带签名消息")


if __name__ == "__main__":
    main()
