from typing import Optional

class Severity:
    Info: Severity
    Success: Severity
    Warning: Severity
    Error: Severity
    Critical: Severity
    @property
    def color(self) -> str: ...
    @property
    def name(self) -> str: ...

class Card:
    def __init__(self) -> None: ...
    def severity(self, severity: Severity) -> Card: ...
    def title(self, title: str) -> Card: ...
    def summary(self, summary: str) -> Card: ...
    def service(self, service: str) -> Card: ...
    def environment(self, environment: str) -> Card: ...
    def timestamp(self, timestamp: str) -> Card: ...
    def details(self, details: str) -> Card: ...
    def note(self, note: str) -> Card: ...
    def field(self, label: str, value: str) -> Card: ...
    def to_json(self) -> str: ...

class TextMessage:
    def __init__(self, text: str) -> None: ...
    @property
    def text(self) -> str: ...
    def to_json(self) -> str: ...

class PostMessage:
    def __init__(self, title: str) -> None: ...
    def text_line(self, text: str) -> PostMessage: ...
    def to_json(self) -> str: ...

class LarkAlert:
    def __init__(
        self,
        webhook_url: str,
        secret: Optional[str] = None,
        timeout_secs: Optional[int] = None,
        max_retries: Optional[int] = None,
    ) -> None: ...
    def send_text(self, text: str) -> None: ...
    def send_post(self, message: PostMessage) -> None: ...
    def send_card(self, card: Card) -> None: ...
